/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as ApiDatasetsRouteImport } from './routes/api/datasets'
import { Route as ApiDatasetsStatsRouteImport } from './routes/api/datasets.stats'
import { Route as ApiDatasetsIdRouteImport } from './routes/api/datasets.$id'

const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const ApiDatasetsRoute = ApiDatasetsRouteImport.update({
  id: '/api/datasets',
  path: '/api/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasetsStatsRoute = ApiDatasetsStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiDatasetsRoute,
} as any)
const ApiDatasetsIdRoute = ApiDatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDatasetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/collections/$id': typeof CollectionsIdRoute
  '/collections': typeof CollectionsIndexRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/api/datasets'
    | '/collections/$id'
    | '/collections/'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/datasets'
    | '/collections/$id'
    | '/collections'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/api/datasets'
    | '/collections/$id'
    | '/collections/'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ApiDatasetsRoute: typeof ApiDatasetsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/api/datasets': {
      id: '/api/datasets'
      path: '/api/datasets'
      fullPath: '/api/datasets'
      preLoaderRoute: typeof ApiDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasets/stats': {
      id: '/api/datasets/stats'
      path: '/stats'
      fullPath: '/api/datasets/stats'
      preLoaderRoute: typeof ApiDatasetsStatsRouteImport
      parentRoute: typeof ApiDatasetsRoute
    }
    '/api/datasets/$id': {
      id: '/api/datasets/$id'
      path: '/$id'
      fullPath: '/api/datasets/$id'
      preLoaderRoute: typeof ApiDatasetsIdRouteImport
      parentRoute: typeof ApiDatasetsRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface ApiDatasetsRouteChildren {
  ApiDatasetsIdRoute: typeof ApiDatasetsIdRoute
  ApiDatasetsStatsRoute: typeof ApiDatasetsStatsRoute
}

const ApiDatasetsRouteChildren: ApiDatasetsRouteChildren = {
  ApiDatasetsIdRoute: ApiDatasetsIdRoute,
  ApiDatasetsStatsRoute: ApiDatasetsStatsRoute,
}

const ApiDatasetsRouteWithChildren = ApiDatasetsRoute._addFileChildren(
  ApiDatasetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ApiDatasetsRoute: ApiDatasetsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
