/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CommonsRouteImport } from './routes/commons'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommonsIndexRouteImport } from './routes/commons.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ApiDatasetsRouteImport } from './routes/api/datasets'
import { Route as ApiCollectionsRouteImport } from './routes/api/collections'
import { Route as ApiDatasetsStatsRouteImport } from './routes/api/datasets.stats'
import { Route as ApiDatasetsIdRouteImport } from './routes/api/datasets.$id'
import { Route as ApiCollectionsSlugRouteImport } from './routes/api/collections.$slug'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug'
import { Route as ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteImport } from './routes/api/collections.$collectionSlug.datasets.$datasetSlug'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.index'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.viewer'
import { Route as ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport } from './routes/api/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug'
import { Route as ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRouteImport } from './routes/api/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.sources.$sourceId.download-zip'

const CommonsRoute = CommonsRouteImport.update({
  id: '/commons',
  path: '/commons',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonsIndexRoute = CommonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommonsRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const ApiDatasetsRoute = ApiDatasetsRouteImport.update({
  id: '/api/datasets',
  path: '/api/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsRoute = ApiCollectionsRouteImport.update({
  id: '/api/collections',
  path: '/api/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasetsStatsRoute = ApiDatasetsStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiDatasetsRoute,
} as any)
const ApiDatasetsIdRoute = ApiDatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDatasetsRoute,
} as any)
const ApiCollectionsSlugRoute = ApiCollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiCollectionsRoute,
} as any)
const CollectionsCollectionSlugDatasetsDatasetSlugRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugRouteImport.update({
    id: '/$collectionSlug/datasets/$datasetSlug',
    path: '/$collectionSlug/datasets/$datasetSlug',
    getParentRoute: () => CollectionsRoute,
  } as any)
const ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteImport.update({
    id: '/$collectionSlug/datasets/$datasetSlug',
    path: '/$collectionSlug/datasets/$datasetSlug',
    getParentRoute: () => ApiCollectionsRoute,
  } as any)
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport.update({
    id: '/files/$fileSlug',
    path: '/files/$fileSlug',
    getParentRoute: () => CollectionsCollectionSlugDatasetsDatasetSlugRoute,
  } as any)
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRouteImport.update(
    {
      id: '/viewer',
      path: '/viewer',
      getParentRoute: () =>
        CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )
const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport.update(
    {
      id: '/files/$fileSlug',
      path: '/files/$fileSlug',
      getParentRoute: () =>
        ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute,
    } as any,
  )
const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRouteImport.update(
    {
      id: '/sources/$sourceId/download-zip',
      path: '/sources/$sourceId/download-zip',
      getParentRoute: () =>
        ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/commons': typeof CommonsRouteWithChildren
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/commons/': typeof CommonsIndexRoute
  '/api/collections/$slug': typeof ApiCollectionsSlugRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
  '/collections/$collectionSlug/datasets/$datasetSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/about': typeof AboutIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/commons': typeof CommonsIndexRoute
  '/api/collections/$slug': typeof ApiCollectionsSlugRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
  '/collections/$collectionSlug/datasets/$datasetSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/commons': typeof CommonsRouteWithChildren
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/commons/': typeof CommonsIndexRoute
  '/api/collections/$slug': typeof ApiCollectionsSlugRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
  '/collections/$collectionSlug/datasets/$datasetSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/commons'
    | '/api/collections'
    | '/api/datasets'
    | '/collections/$slug'
    | '/about/'
    | '/collections/'
    | '/commons/'
    | '/api/collections/$slug'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
    | '/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/collections'
    | '/api/datasets'
    | '/collections/$slug'
    | '/about'
    | '/collections'
    | '/commons'
    | '/api/collections/$slug'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
    | '/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/commons'
    | '/api/collections'
    | '/api/datasets'
    | '/collections/$slug'
    | '/about/'
    | '/collections/'
    | '/commons/'
    | '/api/collections/$slug'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
    | '/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CommonsRoute: typeof CommonsRouteWithChildren
  ApiCollectionsRoute: typeof ApiCollectionsRouteWithChildren
  ApiDatasetsRoute: typeof ApiDatasetsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/commons': {
      id: '/commons'
      path: '/commons'
      fullPath: '/commons'
      preLoaderRoute: typeof CommonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commons/': {
      id: '/commons/'
      path: '/'
      fullPath: '/commons/'
      preLoaderRoute: typeof CommonsIndexRouteImport
      parentRoute: typeof CommonsRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/api/datasets': {
      id: '/api/datasets'
      path: '/api/datasets'
      fullPath: '/api/datasets'
      preLoaderRoute: typeof ApiDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections': {
      id: '/api/collections'
      path: '/api/collections'
      fullPath: '/api/collections'
      preLoaderRoute: typeof ApiCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasets/stats': {
      id: '/api/datasets/stats'
      path: '/stats'
      fullPath: '/api/datasets/stats'
      preLoaderRoute: typeof ApiDatasetsStatsRouteImport
      parentRoute: typeof ApiDatasetsRoute
    }
    '/api/datasets/$id': {
      id: '/api/datasets/$id'
      path: '/$id'
      fullPath: '/api/datasets/$id'
      preLoaderRoute: typeof ApiDatasetsIdRouteImport
      parentRoute: typeof ApiDatasetsRoute
    }
    '/api/collections/$slug': {
      id: '/api/collections/$slug'
      path: '/$slug'
      fullPath: '/api/collections/$slug'
      preLoaderRoute: typeof ApiCollectionsSlugRouteImport
      parentRoute: typeof ApiCollectionsRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug'
      path: '/$collectionSlug/datasets/$datasetSlug'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/api/collections/$collectionSlug/datasets/$datasetSlug': {
      id: '/api/collections/$collectionSlug/datasets/$datasetSlug'
      path: '/$collectionSlug/datasets/$datasetSlug'
      fullPath: '/api/collections/$collectionSlug/datasets/$datasetSlug'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteImport
      parentRoute: typeof ApiCollectionsRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      path: '/files/$fileSlug'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
      path: '/'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
      path: '/viewer'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
    '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': {
      id: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      path: '/files/$fileSlug'
      fullPath: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport
      parentRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute
    }
    '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': {
      id: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
      path: '/sources/$sourceId/download-zip'
      fullPath: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRouteImport
      parentRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
  }
}

interface AboutRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren {
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
}

const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren: CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren =
  {
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute,
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute,
  }

const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute._addFileChildren(
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren,
  )

interface CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren {
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
}

const CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren: CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren =
  {
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren,
  }

const CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren =
  CollectionsCollectionSlugDatasetsDatasetSlugRoute._addFileChildren(
    CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren,
  )

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CollectionsCollectionSlugDatasetsDatasetSlugRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CollectionsCollectionSlugDatasetsDatasetSlugRoute:
    CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface CommonsRouteChildren {
  CommonsIndexRoute: typeof CommonsIndexRoute
}

const CommonsRouteChildren: CommonsRouteChildren = {
  CommonsIndexRoute: CommonsIndexRoute,
}

const CommonsRouteWithChildren =
  CommonsRoute._addFileChildren(CommonsRouteChildren)

interface ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren {
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}

const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren: ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren =
  {
    ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute:
      ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute,
  }

const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute._addFileChildren(
    ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren,
  )

interface ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren {
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
}

const ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren: ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren =
  {
    ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute:
      ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren,
  }

const ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute._addFileChildren(
    ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren,
  )

interface ApiCollectionsRouteChildren {
  ApiCollectionsSlugRoute: typeof ApiCollectionsSlugRoute
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
}

const ApiCollectionsRouteChildren: ApiCollectionsRouteChildren = {
  ApiCollectionsSlugRoute: ApiCollectionsSlugRoute,
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute:
    ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren,
}

const ApiCollectionsRouteWithChildren = ApiCollectionsRoute._addFileChildren(
  ApiCollectionsRouteChildren,
)

interface ApiDatasetsRouteChildren {
  ApiDatasetsIdRoute: typeof ApiDatasetsIdRoute
  ApiDatasetsStatsRoute: typeof ApiDatasetsStatsRoute
}

const ApiDatasetsRouteChildren: ApiDatasetsRouteChildren = {
  ApiDatasetsIdRoute: ApiDatasetsIdRoute,
  ApiDatasetsStatsRoute: ApiDatasetsStatsRoute,
}

const ApiDatasetsRouteWithChildren = ApiDatasetsRoute._addFileChildren(
  ApiDatasetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  CommonsRoute: CommonsRouteWithChildren,
  ApiCollectionsRoute: ApiCollectionsRouteWithChildren,
  ApiDatasetsRoute: ApiDatasetsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
