/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RuntimeConfigDotjsRouteImport } from './routes/runtime-config[.]js'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MapRouteImport } from './routes/map'
import { Route as CommonsRouteImport } from './routes/commons'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommonsIndexRouteImport } from './routes/commons.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDatasetsRouteImport } from './routes/api/datasets'
import { Route as ApiCollectionsRouteImport } from './routes/api/collections'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DotwellKnownApiCatalogRouteRouteImport } from './routes/[.well-known]/api-catalog/route'
import { Route as CollectionsCollectionSlugMapRouteImport } from './routes/collections.$collectionSlug.map'
import { Route as ApiDatasetsStatsRouteImport } from './routes/api/datasets.stats'
import { Route as ApiDatasetsIdRouteImport } from './routes/api/datasets.$id'
import { Route as ApiCollectionsSlugRouteImport } from './routes/api/collections.$slug'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.well-known]/agent-skills/index[.]json'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug'
import { Route as DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRouteImport } from './routes/[.well-known]/agent-skills/hifld-catalog/SKILL[.]md'
import { Route as ApiCollectionsCollectionSlugDatasetsTagsRouteImport } from './routes/api/collections.$collectionSlug.datasets.tags'
import { Route as ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteImport } from './routes/api/collections.$collectionSlug.datasets.$datasetSlug'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.index'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.viewer'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.schema'
import { Route as CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRouteImport } from './routes/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.compare'
import { Route as ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport } from './routes/api/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug'
import { Route as ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRouteImport } from './routes/api/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.schema'
import { Route as ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRouteImport } from './routes/api/collections.$collectionSlug.datasets.$datasetSlug.files.$fileSlug.sources.$sourceId.download-zip'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeConfigDotjsRoute = RuntimeConfigDotjsRouteImport.update({
  id: '/runtime-config.js',
  path: '/runtime-config.js',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonsRoute = CommonsRouteImport.update({
  id: '/commons',
  path: '/commons',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonsIndexRoute = CommonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommonsRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasetsRoute = ApiDatasetsRouteImport.update({
  id: '/api/datasets',
  path: '/api/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsRoute = ApiCollectionsRouteImport.update({
  id: '/api/collections',
  path: '/api/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownApiCatalogRouteRoute =
  DotwellKnownApiCatalogRouteRouteImport.update({
    id: '/.well-known/api-catalog',
    path: '/.well-known/api-catalog',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionSlugMapRoute =
  CollectionsCollectionSlugMapRouteImport.update({
    id: '/$collectionSlug/map',
    path: '/$collectionSlug/map',
    getParentRoute: () => CollectionsRoute,
  } as any)
const ApiDatasetsStatsRoute = ApiDatasetsStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiDatasetsRoute,
} as any)
const ApiDatasetsIdRoute = ApiDatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDatasetsRoute,
} as any)
const ApiCollectionsSlugRoute = ApiCollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiCollectionsRoute,
} as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionSlugDatasetsDatasetSlugRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugRouteImport.update({
    id: '/$collectionSlug/datasets/$datasetSlug',
    path: '/$collectionSlug/datasets/$datasetSlug',
    getParentRoute: () => CollectionsRoute,
  } as any)
const DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute =
  DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRouteImport.update({
    id: '/.well-known/agent-skills/hifld-catalog/SKILL.md',
    path: '/.well-known/agent-skills/hifld-catalog/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionsCollectionSlugDatasetsTagsRoute =
  ApiCollectionsCollectionSlugDatasetsTagsRouteImport.update({
    id: '/$collectionSlug/datasets/tags',
    path: '/$collectionSlug/datasets/tags',
    getParentRoute: () => ApiCollectionsRoute,
  } as any)
const ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteImport.update({
    id: '/$collectionSlug/datasets/$datasetSlug',
    path: '/$collectionSlug/datasets/$datasetSlug',
    getParentRoute: () => ApiCollectionsRoute,
  } as any)
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport.update({
    id: '/files/$fileSlug',
    path: '/files/$fileSlug',
    getParentRoute: () => CollectionsCollectionSlugDatasetsDatasetSlugRoute,
  } as any)
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRouteImport.update(
    {
      id: '/viewer',
      path: '/viewer',
      getParentRoute: () =>
        CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRouteImport.update(
    {
      id: '/schema',
      path: '/schema',
      getParentRoute: () =>
        CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )
const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRouteImport.update(
    {
      id: '/compare',
      path: '/compare',
      getParentRoute: () =>
        CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )
const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport.update(
    {
      id: '/files/$fileSlug',
      path: '/files/$fileSlug',
      getParentRoute: () =>
        ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute,
    } as any,
  )
const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRouteImport.update(
    {
      id: '/schema',
      path: '/schema',
      getParentRoute: () =>
        ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )
const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRouteImport.update(
    {
      id: '/sources/$sourceId/download-zip',
      path: '/sources/$sourceId/download-zip',
      getParentRoute: () =>
        ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/commons': typeof CommonsRouteWithChildren
  '/map': typeof MapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/runtime-config.js': typeof RuntimeConfigDotjsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRouteRoute
  '/api/$': typeof ApiSplatRoute
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/api': typeof ApiIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/commons/': typeof CommonsIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/api/collections/$slug': typeof ApiCollectionsSlugRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
  '/collections/$collectionSlug/map': typeof CollectionsCollectionSlugMapRoute
  '/.well-known/agent-skills/hifld-catalog/SKILL.md': typeof DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute
  '/collections/$collectionSlug/datasets/$datasetSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/tags': typeof ApiCollectionsCollectionSlugDatasetsTagsRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/runtime-config.js': typeof RuntimeConfigDotjsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRouteRoute
  '/api/$': typeof ApiSplatRoute
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/about': typeof AboutIndexRoute
  '/api': typeof ApiIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/commons': typeof CommonsIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/api/collections/$slug': typeof ApiCollectionsSlugRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
  '/collections/$collectionSlug/map': typeof CollectionsCollectionSlugMapRoute
  '/.well-known/agent-skills/hifld-catalog/SKILL.md': typeof DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute
  '/collections/$collectionSlug/datasets/$datasetSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/tags': typeof ApiCollectionsCollectionSlugDatasetsTagsRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/commons': typeof CommonsRouteWithChildren
  '/map': typeof MapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/runtime-config.js': typeof RuntimeConfigDotjsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRouteRoute
  '/api/$': typeof ApiSplatRoute
  '/api/collections': typeof ApiCollectionsRouteWithChildren
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/api/': typeof ApiIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/commons/': typeof CommonsIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/api/collections/$slug': typeof ApiCollectionsSlugRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/datasets/stats': typeof ApiDatasetsStatsRoute
  '/collections/$collectionSlug/map': typeof CollectionsCollectionSlugMapRoute
  '/.well-known/agent-skills/hifld-catalog/SKILL.md': typeof DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute
  '/collections/$collectionSlug/datasets/$datasetSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/tags': typeof ApiCollectionsCollectionSlugDatasetsTagsRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/': typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/commons'
    | '/map'
    | '/robots.txt'
    | '/runtime-config.js'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/api/$'
    | '/api/collections'
    | '/api/datasets'
    | '/api/health'
    | '/api/openapi'
    | '/collections/$slug'
    | '/about/'
    | '/api'
    | '/collections/'
    | '/commons/'
    | '/.well-known/agent-skills/index.json'
    | '/api/collections/$slug'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
    | '/collections/$collectionSlug/map'
    | '/.well-known/agent-skills/hifld-catalog/SKILL.md'
    | '/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/tags'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/robots.txt'
    | '/runtime-config.js'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/api/$'
    | '/api/collections'
    | '/api/datasets'
    | '/api/health'
    | '/api/openapi'
    | '/collections/$slug'
    | '/about'
    | '/api'
    | '/collections'
    | '/commons'
    | '/.well-known/agent-skills/index.json'
    | '/api/collections/$slug'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
    | '/collections/$collectionSlug/map'
    | '/.well-known/agent-skills/hifld-catalog/SKILL.md'
    | '/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/tags'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/commons'
    | '/map'
    | '/robots.txt'
    | '/runtime-config.js'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/api/$'
    | '/api/collections'
    | '/api/datasets'
    | '/api/health'
    | '/api/openapi'
    | '/collections/$slug'
    | '/about/'
    | '/api/'
    | '/collections/'
    | '/commons/'
    | '/.well-known/agent-skills/index.json'
    | '/api/collections/$slug'
    | '/api/datasets/$id'
    | '/api/datasets/stats'
    | '/collections/$collectionSlug/map'
    | '/.well-known/agent-skills/hifld-catalog/SKILL.md'
    | '/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug'
    | '/api/collections/$collectionSlug/datasets/tags'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
    | '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
    | '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CommonsRoute: typeof CommonsRouteWithChildren
  MapRoute: typeof MapRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RuntimeConfigDotjsRoute: typeof RuntimeConfigDotjsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRouteRoute: typeof DotwellKnownApiCatalogRouteRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiCollectionsRoute: typeof ApiCollectionsRouteWithChildren
  ApiDatasetsRoute: typeof ApiDatasetsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  ApiIndexRoute: typeof ApiIndexRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute: typeof DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-config.js': {
      id: '/runtime-config.js'
      path: '/runtime-config.js'
      fullPath: '/runtime-config.js'
      preLoaderRoute: typeof RuntimeConfigDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commons': {
      id: '/commons'
      path: '/commons'
      fullPath: '/commons'
      preLoaderRoute: typeof CommonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commons/': {
      id: '/commons/'
      path: '/'
      fullPath: '/commons/'
      preLoaderRoute: typeof CommonsIndexRouteImport
      parentRoute: typeof CommonsRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasets': {
      id: '/api/datasets'
      path: '/api/datasets'
      fullPath: '/api/datasets'
      preLoaderRoute: typeof ApiDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections': {
      id: '/api/collections'
      path: '/api/collections'
      fullPath: '/api/collections'
      preLoaderRoute: typeof ApiCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionSlug/map': {
      id: '/collections/$collectionSlug/map'
      path: '/$collectionSlug/map'
      fullPath: '/collections/$collectionSlug/map'
      preLoaderRoute: typeof CollectionsCollectionSlugMapRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/api/datasets/stats': {
      id: '/api/datasets/stats'
      path: '/stats'
      fullPath: '/api/datasets/stats'
      preLoaderRoute: typeof ApiDatasetsStatsRouteImport
      parentRoute: typeof ApiDatasetsRoute
    }
    '/api/datasets/$id': {
      id: '/api/datasets/$id'
      path: '/$id'
      fullPath: '/api/datasets/$id'
      preLoaderRoute: typeof ApiDatasetsIdRouteImport
      parentRoute: typeof ApiDatasetsRoute
    }
    '/api/collections/$slug': {
      id: '/api/collections/$slug'
      path: '/$slug'
      fullPath: '/api/collections/$slug'
      preLoaderRoute: typeof ApiCollectionsSlugRouteImport
      parentRoute: typeof ApiCollectionsRoute
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionSlug/datasets/$datasetSlug': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug'
      path: '/$collectionSlug/datasets/$datasetSlug'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/.well-known/agent-skills/hifld-catalog/SKILL.md': {
      id: '/.well-known/agent-skills/hifld-catalog/SKILL.md'
      path: '/.well-known/agent-skills/hifld-catalog/SKILL.md'
      fullPath: '/.well-known/agent-skills/hifld-catalog/SKILL.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections/$collectionSlug/datasets/tags': {
      id: '/api/collections/$collectionSlug/datasets/tags'
      path: '/$collectionSlug/datasets/tags'
      fullPath: '/api/collections/$collectionSlug/datasets/tags'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsTagsRouteImport
      parentRoute: typeof ApiCollectionsRoute
    }
    '/api/collections/$collectionSlug/datasets/$datasetSlug': {
      id: '/api/collections/$collectionSlug/datasets/$datasetSlug'
      path: '/$collectionSlug/datasets/$datasetSlug'
      fullPath: '/api/collections/$collectionSlug/datasets/$datasetSlug'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteImport
      parentRoute: typeof ApiCollectionsRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      path: '/files/$fileSlug'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
      path: '/'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
      path: '/viewer'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/viewer'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
      path: '/schema'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
    '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare': {
      id: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare'
      path: '/compare'
      fullPath: '/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/compare'
      preLoaderRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRouteImport
      parentRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
    '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug': {
      id: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      path: '/files/$fileSlug'
      fullPath: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteImport
      parentRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute
    }
    '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema': {
      id: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
      path: '/schema'
      fullPath: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/schema'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRouteImport
      parentRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
    '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip': {
      id: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
      path: '/sources/$sourceId/download-zip'
      fullPath: '/api/collections/$collectionSlug/datasets/$datasetSlug/files/$fileSlug/sources/$sourceId/download-zip'
      preLoaderRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRouteImport
      parentRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute
    }
  }
}

interface AboutRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren {
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute
}

const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren: CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren =
  {
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugCompareRoute,
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute,
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugViewerRoute,
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugIndexRoute,
  }

const CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren =
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute._addFileChildren(
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren,
  )

interface CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren {
  CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
}

const CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren: CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren =
  {
    CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute:
      CollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren,
  }

const CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren =
  CollectionsCollectionSlugDatasetsDatasetSlugRoute._addFileChildren(
    CollectionsCollectionSlugDatasetsDatasetSlugRouteChildren,
  )

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CollectionsCollectionSlugMapRoute: typeof CollectionsCollectionSlugMapRoute
  CollectionsCollectionSlugDatasetsDatasetSlugRoute: typeof CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CollectionsCollectionSlugMapRoute: CollectionsCollectionSlugMapRoute,
  CollectionsCollectionSlugDatasetsDatasetSlugRoute:
    CollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface CommonsRouteChildren {
  CommonsIndexRoute: typeof CommonsIndexRoute
}

const CommonsRouteChildren: CommonsRouteChildren = {
  CommonsIndexRoute: CommonsIndexRoute,
}

const CommonsRouteWithChildren =
  CommonsRoute._addFileChildren(CommonsRouteChildren)

interface ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren {
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute
}

const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren: ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren =
  {
    ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute:
      ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSchemaRoute,
    ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute:
      ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugSourcesSourceIdDownloadZipRoute,
  }

const ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute._addFileChildren(
    ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteChildren,
  )

interface ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren {
  ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren
}

const ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren: ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren =
  {
    ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRoute:
      ApiCollectionsCollectionSlugDatasetsDatasetSlugFilesFileSlugRouteWithChildren,
  }

const ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren =
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute._addFileChildren(
    ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteChildren,
  )

interface ApiCollectionsRouteChildren {
  ApiCollectionsSlugRoute: typeof ApiCollectionsSlugRoute
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute: typeof ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren
  ApiCollectionsCollectionSlugDatasetsTagsRoute: typeof ApiCollectionsCollectionSlugDatasetsTagsRoute
}

const ApiCollectionsRouteChildren: ApiCollectionsRouteChildren = {
  ApiCollectionsSlugRoute: ApiCollectionsSlugRoute,
  ApiCollectionsCollectionSlugDatasetsDatasetSlugRoute:
    ApiCollectionsCollectionSlugDatasetsDatasetSlugRouteWithChildren,
  ApiCollectionsCollectionSlugDatasetsTagsRoute:
    ApiCollectionsCollectionSlugDatasetsTagsRoute,
}

const ApiCollectionsRouteWithChildren = ApiCollectionsRoute._addFileChildren(
  ApiCollectionsRouteChildren,
)

interface ApiDatasetsRouteChildren {
  ApiDatasetsIdRoute: typeof ApiDatasetsIdRoute
  ApiDatasetsStatsRoute: typeof ApiDatasetsStatsRoute
}

const ApiDatasetsRouteChildren: ApiDatasetsRouteChildren = {
  ApiDatasetsIdRoute: ApiDatasetsIdRoute,
  ApiDatasetsStatsRoute: ApiDatasetsStatsRoute,
}

const ApiDatasetsRouteWithChildren = ApiDatasetsRoute._addFileChildren(
  ApiDatasetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  CommonsRoute: CommonsRouteWithChildren,
  MapRoute: MapRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RuntimeConfigDotjsRoute: RuntimeConfigDotjsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRouteRoute: DotwellKnownApiCatalogRouteRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiCollectionsRoute: ApiCollectionsRouteWithChildren,
  ApiDatasetsRoute: ApiDatasetsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  ApiIndexRoute: ApiIndexRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute:
    DotwellKnownAgentSkillsHifldCatalogSKILLDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
