from pygeoapi.api import JsonValue

class ProviderConnectionError(Exception): ...
class ProviderItemNotFoundError(Exception): ...
class ProviderQueryError(Exception): ...

class BaseProvider:
    data: str
    def __init__(self, provider_def: dict[str, str]) -> None: ...
    def get_fields(self) -> dict[str, dict[str, str]]: ...
    def get_schema(self, schema_type: str = ...) -> tuple[str, dict[str, JsonValue]]: ...
    def query(
        self, offset: int = ..., limit: int = ..., resulttype: str = ..., **kwargs: object
    ) -> dict[str, JsonValue]: ...
    def get(self, identifier: str, **kwargs: object) -> dict[str, JsonValue]: ...
