#!/bin/bash
set -e

# GeoServer data directory
# GeoServer uses /usr/share/geoserver/webapps/geoserver/data by default
# The GEOSERVER_DATA_DIR env var is for reference, but GeoServer's actual data dir is fixed
GEOSERVER_DATA_DIR="/usr/share/geoserver/webapps/geoserver/data"

# Database connection parameters from environment variables
DB_HOST="${DB_HOST:-geoserver-postgres}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-geoserver}"
DB_USER="${DB_USER:-geoserver}"
DB_PASSWORD="${DB_PASSWORD:-geoserver}"

echo "Starting GeoServer with JDBCConfig auto-configuration..."

# Wait for PostgreSQL to be ready (if using local database)
if [ -n "$DB_HOST" ] && [ "$DB_HOST" != "localhost" ] && [ "$DB_HOST" != "127.0.0.1" ]; then
    echo "Waiting for PostgreSQL at $DB_HOST:$DB_PORT to be ready..."
    # Try pg_isready first, fall back to netcat if not available
    until (pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" 2>/dev/null) || (command -v nc >/dev/null && nc -z "$DB_HOST" "$DB_PORT" 2>/dev/null) || (timeout 1 bash -c "cat < /dev/null > /dev/tcp/$DB_HOST/$DB_PORT" 2>/dev/null); do
        echo "PostgreSQL is unavailable - sleeping"
        sleep 2
    done
    echo "PostgreSQL is ready!"
fi

# Create jdbcconfig directory if it doesn't exist
JDBCCONFIG_DIR="$GEOSERVER_DATA_DIR/jdbcconfig"
if [ ! -d "$JDBCCONFIG_DIR" ]; then
    echo "Creating jdbcconfig directory..."
    mkdir -p "$JDBCCONFIG_DIR"
fi

# Configure JDBCConfig if properties file doesn't exist or is not configured
JDBCCONFIG_PROPERTIES="$JDBCCONFIG_DIR/jdbcconfig.properties"
if [ ! -f "$JDBCCONFIG_PROPERTIES" ] || ! grep -q "enabled=true" "$JDBCCONFIG_PROPERTIES" 2>/dev/null; then
    echo "Configuring JDBCConfig for PostgreSQL..."
    cat > "$JDBCCONFIG_PROPERTIES" << EOF
# JDBCConfig properties for PostgreSQL
# Auto-generated by docker-entrypoint.sh
# See: https://docs.geoserver.org/main/en/user/community/jdbcconfig/configuration.html

# Enable JDBCConfig
enabled=true

# Initialize database (creates tables on first run)
initdb=true

# Import existing catalog from XML files to database
import=true

# Direct JDBC Connection
jdbcUrl=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
username=${DB_USER}
password=${DB_PASSWORD}

# Connection pool settings
pool.minIdle=2
pool.maxActive=10
pool.poolPreparedStatements=true
pool.maxOpenPreparedStatements=50
pool.testOnBorrow=true
pool.validationQuery=SELECT 1
pool.testWhileIdle=true
pool.setTimeBetweenEvictionRunsMillis=60000
EOF
    echo "JDBCConfig properties file created at $JDBCCONFIG_PROPERTIES"
else
    echo "JDBCConfig properties file already exists, skipping configuration"
fi

# Start GeoServer
echo "Starting GeoServer..."
exec /usr/share/geoserver/bin/startup.sh

