from pygeoapi.api import API, APIRequest, ApiResult

def get_collection_queryables(api: API, request: APIRequest, dataset: str) -> ApiResult: ...
def get_collection_items(api: API, request: APIRequest, dataset: str) -> ApiResult: ...
def get_collection_item(
    api: API, request: APIRequest, dataset: str, identifier: str
) -> ApiResult: ...
