/** Properties generated by the query tile wrapper rather than the source data. */
export const QUERY_MVT_FEATURE_ID_PROPERTY = "_mcp_feature_id" as const;
export const QUERY_MVT_FEATURE_HASH_PROPERTY = "__hifld_feature_hash" as const;
export const QUERY_MVT_FEATURE_KEY_PROPERTY = "__hifld_feature_key" as const;
export const QUERY_MVT_CENTROID_LNG_PROPERTY = "__hifld_centroid_lng" as const;
export const QUERY_MVT_CENTROID_LAT_PROPERTY = "__hifld_centroid_lat" as const;

export const QUERY_MVT_RESERVED_PROPERTY_NAMES = [
  QUERY_MVT_FEATURE_ID_PROPERTY,
  QUERY_MVT_FEATURE_HASH_PROPERTY,
  QUERY_MVT_FEATURE_KEY_PROPERTY,
  QUERY_MVT_CENTROID_LNG_PROPERTY,
  QUERY_MVT_CENTROID_LAT_PROPERTY,
] as const;

const queryMvtReservedPropertyNames: ReadonlySet<string> = new Set(QUERY_MVT_RESERVED_PROPERTY_NAMES);

export function isQueryMvtReservedProperty(propertyName: string): boolean {
  return queryMvtReservedPropertyNames.has(propertyName);
}
